//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCatalogDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumSong
    {
        public int AlbumYear { get; set; }
        public string AlbumTitle { get; set; }
        public string SongTitle { get; set; }
        public int ArtistID { get; set; }
        public int SongTrackNumber { get; set; }
        public int GenreID { get; set; }
        public int SongTrackLength { get; set; }
        public int SongRating { get; set; }
        public int SongID { get; set; }
        public int AlbumID { get; set; }
    }
}
