//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCatalogDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumByGenre
    {
        public int GenreID { get; set; }
        public string GenreName { get; set; }
        public int AlbumID { get; set; }
    }
}
